services:
  yt-worker:
    build: .
    ports:
      - "8080:8080"
    environment:
      MEDIA_ROOT: /data
      CACHE_TTL_SECONDS: "86400"
      YTDLP_UA: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36"
      YTDLP_COOKIES_B64: "${YTDLP_COOKIES_B64}"
    volumes:
      - ./media:/data
